version: "3.9"

services:
  product-service:
    build: ./services/product_service
    ports:
      - "5001:5001"

  inventory-service:
    build: ./services/inventory_service
    ports:
      - "5002:5002"

  cart-service:
    build: ./services/cart_service
    ports:
      - "5003:5003"

  payment-service:
    build: ./services/payment_service
    ports:
      - "5004:5004"

  order-service:
    build: ./services/order_service
    ports:
      - "5005:5005"

